# name: Docker Image CI

# on:
#   push:
#     branches: [v*]
#   pull_request:
#     branches: [v*]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2
