name: Docker Image CI

on:
  push:
    branches: [ v* ]
  pull_request:
    branches: [ v* ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag SCys/GoalKeepr:$(date +%s)
